framework:
    default_locale: fr   # Change la langue par défaut en français
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr  # Utilise le français comme langue de repli
        providers:
