vich_uploader:
    db_driver: orm
    mappings:
        article_photo:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: vich_uploader.namer_uniqid
            directory_namer: vich_uploader.directory_namer_relative
            delete_on_update: true
            delete_on_remove: true
